apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels: 
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector: 
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
