apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
